### PR TITLE
Create .prettierignore

### PR DESCRIPTION
**Pull request by codefriar**
brings .prettierignore in line with lwc-recipes

### CODE REVIEW

**Comment by codefriar** [comment]
closes #51

**Comment by codefriar** [comment]
@pozil @muenzpraeger - Please do review this one. While the CI check for branch name *was* failing, the log shows two subsequent passes. I don't know why the red x isn't going away.

**Comment by pozil** [comment]
For some reason the CI job that fails is tied to your previous branch name `codefriar-patch-1-1`. Re-running doesn't seem to update that value.
I am also surprised to see that CI triplicated this job (it should just restart it). René can force the merge with admin rights.

**Comment by codefriar** [comment]
I closed that PR, and am re-creating.

I don’t think GitHub actions is … quite there yet.

**Pull request closed without merging**
