### PR TITLE
Codecov setup

### PR DESCRIPTION
**Pull request by pozil**
Set up codecov and a first LWC test

### CODE REVIEW

**Comment by codefriar** [comment]
Is this just for lwc? Or does it include code cov for swift?

**Comment by pozil** [comment]
This PR only covers LWC and Apex in order to align with other sample apps.
If we want to add Swift, we'll need to mount the Swift env in CI and run the tests first. I'll add that to my tooling maintenance/todo list.

**Comment by muenzpraeger** [comment]
Before we talk about adding Swift tests I'd like to see an analysis of what's needed, and estimated run time of these tests, as macOS build have a 10x billing factor.

**Comment by codefriar** [comment]
Before I go that far I need to actually write the unit tests for swift. ;)

**Comment by muenzpraeger** [comment]
LOL - let's postpone this for some time, until there will be the next round of significant changes to the iOS part. FYI @pozil

**Comment by pozil** [comment]
@muenzpraeger I don't think that we pay for [public repos](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions):
> GitHub Actions usage is free for public repositories.

The way I understand it, the billing per minute scheme is only for private repos.

**Comment by muenzpraeger** [comment]
Potentially, although I don't know the exact terms of the contract, so I just want to be cautious.

**Comment by codefriar** [comment]
So... this dec/Jan.

**Pull request merged**
